# ========================================# ========================================

# FileName: build.yaml# FileName: build.yaml

# Date: 22.09.2025# Date: 22.09.2025

# Brief: Custom Split Keyboard Configuration# Brief: Custom Split Keyboard Configuration

# Board: nice_nano_v2 (SuperMini nRF52840 compatible)# Board: nice_nano_v2 (SuperMini nRF52840 compatible)

# ========================================# ========================================



------

include:include:

  ### CUSTOM SPLIT KEYBOARD ONLY ###  ### CUSTOM SPLIT KEYBOARD ONLY ###

  - board: nice_nano_v2  - board: nice_nano_v2

    shield: custom_split_left    shield: custom_split_left

    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"CustomSplit\" -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"CustomSplit\" -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000

    artifact-name: nice_custom_split_left    artifact-name: nice_custom_split_left

    snippet: studio-rpc-usb-uart    snippet: studio-rpc-usb-uart

  - board: nice_nano_v2  - board: nice_nano_v2

    shield: custom_split_right    shield: custom_split_right

    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000

    artifact-name: nice_custom_split_right    artifact-name: nice_custom_split_right
  - board: puchi_ble_v1
    shield: corne_left nice_oled
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Puchi_Corne_O\"
    artifact-name: puchi_corne_left_oled
    snippet: studio-rpc-usb-uart
  - board: puchi_ble_v1
    shield: corne_right nice_oled
    artifact-name: puchi_corne_right_oled

    # peripheral_left + nice_nano_v2 + nice_oled
  - board: nice_nano_v2
    shield: corne_left_peripheral nice_oled
    artifact-name: nice_corne_left_peripheral_oled

    # peripheral_left + puchi_ble_v1 + nice_oled
  - board: puchi_ble_v1
    shield: corne_left_peripheral nice_oled
    artifact-name: puchi_corne_left_peripheral_oled
    ### nice_oled END ###

    ### Xiao_Dongle START ###
  - board: seeeduino_xiao_ble
    shield: corne_dongle_xiao
    #  -DCONFIG_ZMK_USB=y  -DCONFIG_ZMK_BLE=y
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Xiao_Dongle\" -DCONFIG_ZMK_STUDIO=y
    artifact-name: xiao_corne_dongle
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: corne_dongle_xiao dongle_display
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Xiao_Dongle_O\"
    artifact-name: xiao_corne_dongle_oled
    snippet: studio-rpc-usb-uart
    # snippet: zmk-usb-logging
    ### Xiao_Dongle END ###

    ### ProMicro_Dongle START ###
    # nice_nano_v2 dongle
  - board: nice_nano_v2
    shield: corne_dongle_pro_micro
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Dongle\"
    artifact-name: nice_corne_dongle_pro_micro
    snippet: studio-rpc-usb-uart
    # snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: corne_dongle_pro_micro dongle_display
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Dongle_O\"
    artifact-name: nice_corne_dongle_oled
    snippet: studio-rpc-usb-uart
    # snippet: zmk-usb-logging
  - board: puchi_ble_v1
    shield: corne_dongle_pro_micro
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Puchi_Dongle\"
    artifact-name: puchi_corne_dongle
    snippet: studio-rpc-usb-uart
    # snippet: zmk-usb-logging
  - board: puchi_ble_v1
    shield: corne_dongle_pro_micro nice_view_adapter nice_epaper
    #  -DCONFIG_ZMK_USB=y  -DCONFIG_ZMK_BLE=y
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Puchi_Dongle_V\"  -DCONFIG_ZMK_STUDIO=y
    snippet: studio-rpc-usb-uart
    artifact-name: puchi_corne_dongle_view
    # snippet: zmk-usb-logging
    ### Pro Micro END ###

    ### ProMicro_Dongle START ###
    # NICE x PUCHI and nice_oled + rgb
  - board: nice_nano_v2
    shield: corne_left nice_oled
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Corne_Oled_RGB\"
    artifact-name: nice_corne_left_oled_rgb
    snippet: rgb-config studio-rpc-usb-uart
  - board: puchi_ble_v1
    shield: corne_right nice_oled
    snippet: rgb-config
    artifact-name: puchi_corne_right_oled_rgb
    ### Pro Micro END ###
  ### CORNE END ###

  ### SOFLEV2 SOFLEV1 SOFLEPLUS START ###
  # nice!oled sofle
  - board: nice_nano_v2
    shield: sofle_left nice_oled
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Sofle_Oled\"  -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_sofle_left_oled
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: sofle_right nice_oled
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_sofle_right_oled

  # peripheral_left
  - board: nice_nano_v2
    shield: sofle_left_peripheral nice_oled
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_sofle_left_peripheral_oled

  # Xiao_Dongle
  - board: seeeduino_xiao_ble
    shield: sofle_dongle_xiao oled_adapter_seeeduino_xiao_ble_128x64 dongle_display
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"SofleDongle_X\" -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: xiao_sofle_dongle_xiao_oled
    snippet: studio-rpc-usb-uart

  # ProMicro_Dongle
  - board: nice_nano_v2
    shield: sofle_dongle_pro_micro dongle_display
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"SofleDongle_P\"  -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SLEEP=n -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_sofle_dongle_oled
    snippet: studio-rpc-usb-uart
  ### SOFLEV2 SOFLEV1 SOFLEPLUS END ###

  ### LILY58 START ###
  # basic lily58 without display
  - board: nice_nano_v2
    shield: lily58_left
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"lily58_Basic\"  -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_lily58_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: lily58_right
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_lily58_right

  # peripheral_left
  - board: nice_nano_v2
    shield: lily58_left_peripheral
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_lily58_left_peripheral

  ### LILY58 END ###

  ### CUSTOM SPLIT START ###
  # Custom split keyboard with nice!nano v2 (SuperMini compatible)
  - board: nice_nano_v2
    shield: custom_split_left
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"CustomSplit\" -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_custom_split_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: custom_split_right
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_custom_split_right
  ### CUSTOM SPLIT END ###

  ### SPLITKB AURORA SOFLE START ###
  # nice!oled splitkb_aurora_sofle
  - board: nice_nano_v2
    shield: splitkb_aurora_sofle_left nice_oled
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"A_Sofle_Oled\"  -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_splitkb_aurora_sofle_left_oled
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: splitkb_aurora_sofle_right nice_oled
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_splitkb_aurora_sofle_right_oled

  # peripheral_left
  - board: nice_nano_v2
    shield: splitkb_aurora_sofle_left_peripheral nice_oled
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_splitkb_aurora_sofle_left_peripheral_oled

  # Xiao_Dongle
  - board: seeeduino_xiao_ble
    shield: splitkb_aurora_sofle_dongle_xiao oled_adapter_seeeduino_xiao_ble_128x64 dongle_display
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"A_SofleDongle_X\" -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: xiao_splitkb_aurora_sofle_dongle_xiao_oled
    snippet: studio-rpc-usb-uart

  # ProMicro_Dongle
  - board: nice_nano_v2
    shield: splitkb_aurora_sofle_dongle_pro_micro dongle_display
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"A_SofleDongle_P\"  -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SLEEP=n -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_splitkb_aurora_sofle_dongle_oled
    snippet: studio-rpc-usb-uart
  ### SPLITKB AURORA SOFLE END ###

  ### SETTINGS_RESET START ###
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xiao_settings_reset
  - board: puchi_ble_v1
    shield: settings_reset
    artifact-name: puchi_settings_reset
  ### SETTINGS_RESET END ###
