include:
  - board: nice_nano_v2
    shield: custom_split_left
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"CustomSplit\" -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_custom_split_left
  - board: nice_nano_v2
    shield: custom_split_right
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_custom_split_right